#!/usr/bin/sh
#
# $Id: restart,v 1.2 2026-07-26 01:17:41+05:30 Cprogrammer Exp mbhangui $
#
for i in librespot squeezelite shairport-sync
do
	if [ -d /service/$i ] ; then
		if [ -z "$svc" ] ; then
			svc="/service/$i"
		else
			svc="$svc /service/$i"
		fi
	fi
done
if [ -d /service/priority ] ; then
	sudo svc -r $svc
	exec sudo svc -o /service/priority
else
	exec sudo svc -r $svc
fi
#
# $Log: restart,v $
# Revision 1.2  2026-07-26 01:17:41+05:30  Cprogrammer
# replace /bin/sh with /usr/bin/sh
#
# Revision 1.1  2026-07-25 00:31:17+05:30  Cprogrammer
# Initial revision
#
#
