#!/bin/sh
case $1 in
	update)
	if [ -f /etc/debian_version ] ; then
		exec sudo env DEBIAN_FRONTEND=noninteractive apt update -y
	elif [ -f /usr/bin/dnf ] ; then
		exec sudo dnf -y update
	fi
	;;
	upgrade)
	if [ -f /etc/debian_version ] ; then
		exec sudo env DEBIAN_FRONTEND=noninteractive apt --allow-downgrades upgrade -y
	else
		exec sudo dnf -y upgrade
	fi
	;;
esac
